name: Publish release

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      created: ${{ steps.release.outputs.created }}
      version: ${{ steps.release.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish release
        id: release
        uses: fdiesel/github-action-node-release@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
          path: ./package.json